### ISSUE TITLE
how to setup/install?

### ISSUE THREAD

**Issue by mertoalex** [SmokinSpectre/Dots#2]
I too using Arch and I want setup this theme how I can ?

**Comment by mertoalex** [comment]
I think I founded I'm trying

**Comment by SmokinSpectre** [comment]
To install these dotfiles you just have to copy all these files over to your home directory. These are the dependencies you need to set these up correctly:
- bspwm
- sxhkd
- picom-jonaburg-git
- polybar
- termite
- zsh, oh-my-zsh, starship
- feh
- dunst
These packages will only provide you with a base install, I use **Iosevka**, **Fira-Code** and **Noto Fonts** but if you don't like them then you can easily replace all of these with ones you like assuming you know the location of these configs. If you need more help then feel free to comment on this issue again, I'll keep it open. Have a nice day :)

**Comment by SmokinSpectre** [comment]
To install these dotfiles you just have to copy all these files over to your home directory. These are the dependencies you need to set these up correctly:
- bspwm
- sxhkd
- picom-jonaburg-git
- polybar
- termite
- zsh, oh-my-zsh, starship
- feh
- dunst
These packages will only provide you with a base install, I use **Iosevka**, **Fira-Code** and **Noto Fonts** but if you don't like them then you can easily replace all of these with ones you like assuming you know the location of these configs. The keybinds to change the theme and other things is managed by `sxhkd` and it's config can be found [here](https://github.com/SmokinSpectre/Dots/blob/Stable/.config/sxhkd/sxhkdrc), You can replace with the ones you are comfortable with too. If  you need more help then feel free to comment on this issue again, I'll keep it open. Have a nice day :)

**Comment by mertoalex** [comment]
TYSM I trying now- wait I downloadin 2 gb file I can't now :man_facepalming: I try in another time TYSM again

**Comment by TheBongoCat** [comment]
Hey sorry, I am from #3. I was not able to see the closed issue section as I am new to GitHub. Could you tell me why you are using **LXDM** as your Display Manager? Isn't it discontinued?

**Comment by SmokinSpectre** [comment]
> Hey sorry, I am from #3. I was not able to see the closed issue section as I am new to GitHub. Could you tell me why you are using **LXDM** as your Display Manager? Isn't it discontinued?

@TheBongoCat No problem, I use LXDM because it offers more customisation than LightDM or any other DE I have used. If you don't like it then you can change it to the one you like.

**Comment by TheBongoCat** [comment]
Thanks! I will close this issue now. Have a nice day :)
