### ISSUE TITLE
New To Linux, Need Help Installing These DotFiles

### ISSUE THREAD

**Issue by TheBongoCat** [SmokinSpectre/Dots#3]
Hey! I really like your Dot Files :)
I am new to Arch Linux and saw a lot of people making custom themes for it on *r/unixporn*. Can you please help me set these up on my machine? It would be greatly appreciated.

**Comment by SmokinSpectre** [comment]
Hey, Kindly refer to #2. I have clearly mentioned the required dependencies and notes to deploy my dotfiles. I have only tested them on my machine  so they might not work as expected on yours. I have switched to **Kiss Linux™** and **Wayland**, So I won't be updating these anymore.

**Comment by TheBongoCat** [comment]
Okay, Thanks :)
